### PR TITLE
A dirty hack to force importing PyDSTool

### LINKED ISSUE #5: Versioning issue with standard installation
https://travis-ci.org/JuliaDiffEq/PyDSTool.jl/jobs/333382020#L690
https://ci.appveyor.com/project/ChrisRackauckas/pydstool-jl/build/1.0.58/job/wfhgp6mq30pnt70g#L382

@isuruf do you what could cause this?

### PR DESCRIPTION
**Pull request by tkf**
closes #5 

(I didn't test anything locally since I don't like Conda.jl...  Let's see if Travis is fine with this patch.)

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Looks like the test fails with this. What exactly is it doing? Just makes it think it's v0.9 to get around the error check?

**Comment by tkf** [comment]
Yea, that what it's doing.

Hmm... I forgot that py" was a macro. Aren't there a way to do exac as a function call? Let's see...

**Comment by tkf** [comment]
Oops, I totally forgot that scipy functions are renamed.  This patch won't work.  :)

**Comment by tkf** [comment]
...unless you patch it all the way down!

**Comment by ChrisRackauckas** [comment]
Well tests pass and it's completely broken right now, and the library looks unmaintained, so this looks like the dirty solution we'll use for now. Thanks for this madness 👍 .

**Pull request merged**
